#!/bin/sh
# Set the screen DPI (uncomment this if needed!)
# xrdb ~/.emacs.d/exwm/Xresources

# Run the screen compositor
picom &

# Swap Capslock with Esc
setxkbmap -option "caps:swapescape"

/home/bruno/.config/polybar/launch.sh --hack &
# Fire it up
exec dbus-launch --exit-with-session emacs -mm --debug-init
